// Generated by datafile. Regenerate with `datafile.py pi-package`.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { spawn } from "node:child_process";

// Resolved where the package runs, never at generation time. An absolute path
// baked in here would name one machine's checkout, and would make the same
// commit generate different bytes in every checkout, so `pi-package --check`
// could only ever pass where the generator last ran.
const COMMAND = "datafile";
const TIMEOUT_MS = 10000;
const HEADER = "## AXI ambient context: datafile";
const NOT_INSTALLED = "pi-datafile: could not run `datafile`, so this session has no ambient store context. Put it on PATH (`just install` in the datafile checkout, or link datafile.py onto PATH as `datafile`), then start a new session.";

// Resolves to the view, to "" when datafile ran but had nothing usable to
// say, or to null when it could not be started at all - the one failure that
// is a setup problem the user can fix rather than a store to read.
function homeView(cwd: string): Promise<string | null> {
  return new Promise((resolve) => {
    const child = spawn(COMMAND, [], {
      cwd,
      env: process.env,
      shell: false,
      stdio: ["ignore", "pipe", "pipe"],
    });
    let out = "";
    let settled = false;
    const done = (value: string | null) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve(value);
    };
    const timer = setTimeout(() => {
      child.kill("SIGTERM");
      done("");            // a slow store is not a missing command
    }, TIMEOUT_MS);
    child.stdout?.setEncoding("utf-8");
    child.stdout?.on("data", (chunk) => {
      out += chunk;
    });
    child.on("error", () => done(null));   // not on PATH, or not executable
    child.on("close", (code) => done(code === 0 ? out.trim() : ""));
  });
}

export default function (pi: ExtensionAPI) {
  let ambient = "";

  pi.on("session_start", async (_event, ctx) => {
    const view = await homeView(ctx.cwd);
    // Ambient context is best-effort: a failure must not corrupt the prompt,
    // so the only thing an unusable datafile costs is the context itself.
    // A missing command is worth one line on stderr, because it is the only
    // failure the reader of that line can do something about.
    if (view === null) console.error(NOT_INSTALLED);
    ambient = view ?? "";
  });

  pi.on("before_agent_start", async (event) => {
    if (!ambient) return;
    return { systemPrompt: `${event.systemPrompt}\n\n${HEADER}\n${ambient}` };
  });
}
